language: python
python:
  - "3.6"

cache: pip


addons:
  postgresql: "9.4"

env:
  - DEBUG=True

services:
  - redis-server

install:
  - pip install -r requirements.txt --quiet
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate
  - python manage.py test
  - coverage run --source=base manage.py test
  - coverage run --source=mail manage.py test

after_success:
- coveralls
